### ISSUE TITLE
Crashes rocket league upon opening

### ISSUE THREAD

**Issue by BTNGaming** [smallest-cock/CustomQuickchat#1]
I messaged you on Youtube before, thought it was fixed, but am still running into not being able to open rocket league with bakkesmod open. It only happens when I have this plugin enabled just so you are aware. If you need anything from me, i'm more than happy to sort through and figure it out with you! Can also hit me up on Discord @ BTNGaming

**Comment by BTNGaming** [comment]
both epic and steam versions just to clarify.

**Comment by smallest-cock** [comment]
@BTNGaming Did it recently start crashing again, or has it been crashing for a while? I ask because I recently updated the `CustomQuickchat.dll` in the release about 3 days ago to use an updated SDK (for the latest RL update). So if you already downloaded/installed the plugin from within the last 3 days, then that might narrow down where the issue is (potentially something in the newer SDK)

On the other hand, if you *haven't* downloaded/installed the latest release from 3 days ago, then I'd recommend trying that, because your crashes could be due to the outdated SDK. Btw you can tell the difference between releases by hovering over the .dll file on your computer and looking at the version number... the newest release is 1.5.3.2 and the older one is 1.5.3.1

**Comment by smallest-cock** [comment]
After troubleshooting on discord, apparently there was a bug causing code in the cvar change callback function for `auto_detect_interpreter_path` to trigger when `config.cfg` is executed (when RL/bakkesmod loads). This caused `findPythonInterpreter()` to be called accidentally, which is known to cause crashes for some users (and is the root cause of this issue... a separate bug in itself)
