### ISSUE TITLE
How to build locally

### ISSUE THREAD

**Issue by Dastan21** [smallest-cock/CustomQuickchat#3]
Hi, I'm trying to build the plugin locally but there are files missing like all `SDK/*`.
I tried getting them from https://github.com/skillor/RL-Template but I get plenty of `error C2027: use of undefined type`.
Any help on how to setup?

**Comment by smallest-cock** [comment]
Yeah the repo is missing the `SDK/*` and `Components/*` files (due to the .gitignore)

The RLSDK in the repo you linked is a year old, so some things may not work properly. The sdk should ideally be updated with every game update. https://github.com/matix2/RLSDK-Generator This config should work (at least for this plugin), you just have to update the offsets in `Engine/RocketLeague/Configuration.cpp`

As far as the missing files, it was originally intended to deter others from easily making/selling paid "RL hax" using pasted code (which seems to be common in RL modding for some reason) but at this point I'm not sure if I care anymore. I'll probably include them in the next update.. just gotta clean up the code a bit. You can also msg me on discord @sslowdev if you would like the files now
